translate group label and header type
bpmn-io/bpmn-js-properties-panel pull request #542
Opened 2022-01-14 09:12 UTC by polarloves

fix bug:https://github.com/bpmn-io/bpmn-js-properties-panel/issues/537

2022-02-03 08:15 UTC, pinussilvestrus commented on src/provider/bpmn/BpmnPropertiesProvider.js
> +        group.label = translate(group.label);
With this one, we would fix the translation for the `bpmn` properties provider only. We have [multiple ones](https://github.com/bpmn-io/bpmn-js-properties-panel/tree/master/src/provider) for different use cases (Camunda Platform vs. Camunda Cloud specific).

Maybe we should add translation there as well?

2022-02-03 08:24 UTC, barmac commented
Instead of monkey-patching the labels, I'd suggest that we translate them explicitly like we already do in the element templates: https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/provider/element-templates/ElementTemplatesPropertiesProvider.js#L100

2022-02-07 12:55 UTC, barmac requested changes
Cf. https://github.com/bpmn-io/bpmn-js-properties-panel/pull/542#issuecomment-1028718716

2022-02-21 08:18 UTC, pinussilvestrus commented
@polarloves any updates on this one?

2022-03-01 08:44 UTC, smbea commented
Since there hasn't been any activity on this pull request, I will be closing it for now.

2022-03-01 08:44 UTC, closed without merging