Add validation to called element `processId` in Call Activity
bpmn-io/bpmn-js-properties-panel pull request #546
Opened 2022-01-17 14:15 UTC by smbea

Closes #346

Uses the same validation as `IdProps`, except:
* field remains non-mandatory 
* don't check if id already assigned because this is used to refer to an existing process Id

2022-01-18 12:32 UTC, pinussilvestrus commented
Works well in general 👍  I'm just wondering: As far as I remember we limit the validation in the properties panel due to a bare minimum because we want to establish linting as the go-to validation.

This since is id validation and with this, we make sure our diagram is sound (don't use invalid ids), I'd agree to add it. Wdyt @MaxTru @nikku @andreasgeier?

(Sorry when this was already clarified somewhere 🙂 )

2022-01-18 16:25 UTC, MaxTru commented
> Works well in general +1 I'm just wondering: As far as I remember we limit the validation in the properties panel due to a bare minimum because we want to establish linting as the go-to validation.
> 
> This since is id validation and with this, we make sure our diagram is sound (don't use invalid ids), I'd agree to add it. Wdyt @MaxTru @nikku @andreasgeier?
> 
> (Sorry when this was already clarified somewhere slightly_smiling_face )

I would be okay with this PR (pragmatic decision, we already validate the ID). Once we have linting, we could easily unbuild.

2022-01-19 09:10 UTC, smbea commented
@nikku @andreasgeier Any thoughts?

2022-01-19 14:12 UTC, MaxTru requested changes
Note that also an expression is valid. C.f. https://docs.camunda.io/docs/components/modeler/bpmn/call-activities/call-activities/#defining-the-called-process

So we would need to invest into the validation (either qname static value of expression). Hence, considering that we anyhow invest into this via linting soon, I would leave it...

2022-01-19 14:15 UTC, smbea commented
> Note that also an expression is valid. C.f. https://docs.camunda.io/docs/components/modeler/bpmn/call-activities/call-activities/#defining-the-called-process
> 
> So we would need to invest into the validation (either qname static value of expression). Hence, considering that we anyhow invest into this via linting soon, I would leave it...

Ok, makes sense. Should I close this PR then?

2022-01-19 14:16 UTC, MaxTru commented
Your call - I would recommend yes :-)

2022-01-19 14:16 UTC, closed without merging