fix(zeebe): delete calledDecision for <none> dmn implementation
bpmn-io/bpmn-js-properties-panel pull request #611
Opened 2022-03-15 08:50 UTC by smbea

Closes #578

2022-03-15 08:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bpmn-io/bpmn-js-properties-panel?pullRequest=611) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bpmn-io/bpmn-js-properties-panel?pullRequest=611) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bpmn-io/bpmn-js-properties-panel?pullRequest=611) it.</sub>

2022-03-15 12:28 UTC, MaxTru requested changes

2022-03-15 12:28 UTC, MaxTru commented on src/provider/zeebe/properties/BusinessRuleImplementationProps.js
> +
```suggestion
```

2022-03-15 12:28 UTC, MaxTru commented on src/provider/zeebe/properties/BusinessRuleImplementationProps.js
> +    resetElement(element, commandStack);
The undo/redo chain is broken if we have this as additional command.

If you for example:
1. Switch to DMN
2. Then switch to Job Worker
3. Then Undo
4. => will result in "none", where it should result in "DMN"

Can you please:
* Execute this within 1 command
* add test case for this bug

2022-03-16 10:35 UTC, smbea commented on src/provider/zeebe/properties/BusinessRuleImplementationProps.js
> +export function updateExtensionElements(element, extensionElementToAdd, bpmnFactory, commandStack) {
No, sorry. It was leftover from adapting an existing function in `ExtensionElementsUtil`. It's a specific case I haven't seen use for elsewhere so I'll just remove the `export`.

2022-03-16 10:39 UTC, smbea commented on src/provider/zeebe/properties/BusinessRuleImplementationProps.js
> +export function updateExtensionElements(element, extensionElementToAdd, bpmnFactory, commandStack) {
done

2022-03-16 10:41 UTC, MaxTru approved these changes
Just removed an unnecessary empty line. 

:wave:

2022-03-16 10:47 UTC, merged