feat(DescriptionProvider): add user and multi-instance task links
bpmn-io/bpmn-js-properties-panel pull request #612
Opened 2022-03-16 13:22 UTC by marstamm

Add doc links for Multi-Instance and Assignment Groups:

![image](https://user-images.githubusercontent.com/21984219/158599094-a7ce1289-815c-4326-a15b-9dd6055af04c.png)

closes #600

2022-03-16 13:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bpmn-io/bpmn-js-properties-panel?pullRequest=612) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bpmn-io/bpmn-js-properties-panel?pullRequest=612) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bpmn-io/bpmn-js-properties-panel?pullRequest=612) it.</sub>

2022-03-16 14:34 UTC, MaxTru requested changes
* I propose to also link to https://docs.camunda.io/docs/components/modeler/bpmn/user-tasks/#user-task-forms `How to link to a Form` for UserTasks here under the select here:
![Screenshot_20220316_152929](https://user-images.githubusercontent.com/42800119/158613175-29a738df-fa62-4bee-a791-f83d673c3b5d.png) - WDYT?
* I think we missed message throw events (https://docs.camunda.io/docs/components/modeler/bpmn/message-events/#message-throw-events)
![Screenshot_20220316_153320](https://user-images.githubusercontent.com/42800119/158614060-41206d7c-13c6-452c-9378-b877094f381b.png)

2022-03-16 15:52 UTC, marstamm commented
Great suggestions with the form and throw events! I'll add those

2022-03-16 15:53 UTC, marstamm commented on src/contextProvider/zeebe/DescriptionProvider.js
> +        { translate('How to configure a multi instance task') }
I'd align it with the documentation we link to. The, "multi instance activity" is used, so let's use this wording

2022-03-17 12:47 UTC, MaxTru approved these changes

2022-03-17 12:47 UTC, merged