chore(CHANGELOG): update to v1.0.0-alpha.11
bpmn-io/bpmn-js-properties-panel pull request #655
Opened 2022-04-04 15:16 UTC by philippfromme

# Changes

## 1.0.0-alpha.11

* `FEAT`: add show callbacks to show erro code and message name errors ([#654](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/654))

2022-04-04 18:07 UTC, MaxTru requested changes
What about

* `FIX`: add properties for `Condition` ([#2866](https://github.com/camunda/camunda-modeler/issues/2866))
* `FEAT`: show element template icons in header (https://github.com/bpmn-io/bpmn-js-properties-panel/commit/de8479f6ed08784503f2e4da5df3b1761c0cc1e3)
* `FEAT`: add icon property during element template application (https://github.com/bpmn-io/bpmn-js-properties-panel/commit/e48b6a21b28227c8ff18194f7111e81d01dce940)
* `CHORE`: all element template choose in dev setup (https://github.com/bpmn-io/bpmn-js-properties-panel/commit/e47642dc8623da965939318c69a0f06e4cca580b)

2022-04-04 18:07 UTC, MaxTru commented on CHANGELOG.md
> +* `FEAT`: add show callbacks to show erro code and message name errors ([#654](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/654))
```suggestion
* `FEAT`: add show callbacks to show error code and message name errors ([#654](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/654))
```

2022-04-05 06:59 UTC, philippfromme commented
Ooops. 🤦🏻

2022-04-05 07:35 UTC, barmac commented
How about if we wait for https://github.com/bpmn-io/bpmn-js-properties-panel/pull/656?

2022-04-05 07:39 UTC, MaxTru commented
> How about if we wait for #656?

Makes sense, can you do the review @barmac ?

2022-04-05 07:43 UTC, barmac commented
Yeah, I am on it right now.

2022-04-05 07:45 UTC, barmac commented
The linked PR will take some time so let's skip it for this release.

2022-04-05 07:53 UTC, MaxTru approved these changes
lgtm

2022-04-05 07:53 UTC, merged