fix: focus form field enum value on create
bpmn-io/bpmn-js-properties-panel pull request #683
Opened 2022-05-17 08:48 UTC by Skaiir

Closes #589

![electron_T2Yl7jVbKt](https://user-images.githubusercontent.com/17801113/168770336-3de019ce-7ebc-47aa-a4b8-0b6e6c370efd.gif)

2022-05-18 05:51 UTC, nikku requested changes
What I'm still missing is scroll to focused element. Without that the change is often times meaningless:

![capture FyL9tz_optimized](https://user-images.githubusercontent.com/58601/168966622-6400126e-7ad4-43cf-a2c3-c069b132db9a.gif)

2022-05-18 05:51 UTC, nikku commented on src/provider/camunda-platform/properties/FormField.js
Please add `Closes #589` to the commit message.

This establishes the relevant context needed to track back the fix to the bug.

2022-05-18 15:16 UTC, Skaiir commented
@nikku I agree with the focus but then that leads to the issue of not being able to pre-create a bunch of fields. 

If you already know you want 6 fields and click the add button a bunch of times, the + button will scroll out of view. But then again, that's already a problem for keyboard users. 

Are we fine to consider everything besides the commit amend another issue / pr? 

The missing scrollIntoView behavior IMO would need to be discussed a bit more. It would make more sense to implement it after https://github.com/camunda/camunda-modeler-design/issues/118, since this will make the + button problem irrelevant. I can set up a ticket for this if that makes sense.

2022-05-18 19:02 UTC, nikku commented
> @nikku I agree with the focus but then that leads to the issue of not being able to pre-create a bunch of fields.

Understood. There is no clear "winner" for UX. On the other hand sections will [some day be sticky](https://github.com/camunda/camunda-modeler-design/issues/118), so important controls won't hopefully vanish too easily from your sight.

Please create another issue for the focus case. I'd love to discuss it with @andreasgeier; maybe we can even ignore it for now.

2022-05-18 19:03 UTC, nikku commented
If you just add the `Closes #asd` comment and we have the follow up issue this one looks ready to merge for me.

2022-05-19 08:21 UTC, Skaiir commented
> If you just add the `Closes #asd` comment and we have the follow up issue this one looks ready to merge for me.

Done, for some reason I thought I already did this 😕

2022-05-19 12:06 UTC, nikku approved these changes
Works for me.

2022-05-19 12:06 UTC, merged