fix(cloud-element-templates): keep template properties order
bpmn-io/bpmn-js-properties-panel pull request #844
Opened 2023-01-03 13:56 UTC by smbea

Closes #838

We could consider refactoring `propertyUtil` later on to not delete the modified properties and just update the values instead, see https://github.com/bpmn-io/bpmn-js-properties-panel/issues/838#issuecomment-1369792405

2023-01-03 15:04 UTC, marstamm requested changes
Good work so far, the implementation works fine for the common use cases with the mappings already present in the XML. There are some edge cases where we have no explicitly defined behavior yet. Specifically, where should new entries be added?

With this PR (and https://github.com/bpmn-io/bpmn-js-properties-panel/pull/843) we are introducing the concept that "order matters". I think it is important to be clear about our story around it. My assumption is, that the order in the XML corresponds to what the order user sees in the properties panel. Is this assumption correct?
In that case, we should insert new and optional properties at the position according to the element template.

Does this make sense? Let me know what you think about this proposal.

2023-01-03 15:05 UTC, marstamm commented on src/provider/cloud-element-templates/util/propertyUtil.js
> +          properties: { values }
> We could consider refactoring this later on to not delete the properties here and just update the values instead, see https://github.com/bpmn-io/bpmn-js-properties-panel/issues/838#issuecomment-1369792405

I did not see your comment about this one, sorry 🙈

2023-01-03 17:14 UTC, nikku commented
Let's move specs for this aspect to a dedicated document: https://github.com/bpmn-io/bpmn-js-properties-panel/compare/838-stable-property-order.

The tests I've added need to be expanded:

* Fix/reorder mappings on modification (automatically heal, if existing ones are broken)?
* New entries are added in the correct places (i.e. when non-existing initially _or_ contitionally activated)

2023-01-04 23:51 UTC, nikku commented on test/spec/provider/cloud-element-templates/fixtures/complex.json
> +  {
Let's not mangle it into `complex.json`, but instead keep it in a separate file, under a clear name, i.e. `update-properties-order.json`.

You can rely on all templates in `cloud-element-templates/fixtures` to be loaded by the test, cf. https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/test/spec/BpmnPropertiesPanelRenderer.spec.js#L245.

2023-01-05 09:25 UTC, nikku commented
I'm end-to-end testing this today. Great work on finding a robust, self-healing solution @smbea @marstamm :medal_sports:.

2023-01-05 19:43 UTC, nikku reviewed
@marstamm You want to give your final approal on this? Looks good to me.

2023-01-06 07:57 UTC, marstamm approved these changes
Great work @smbea , works like a charm

2023-01-06 08:00 UTC, merged